### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by rvlander** [nasa/europa#178]
There haven't been much activity for years. It may be because the project is stable and does not need any updates or because the project is now is unmaintained or replaced by a newer one.

What is the status of this project? Is it a good idea to start a new planning application based on it?

Thanks,

**Comment by miatauro-NASA** [comment]
Hi, @rvlander!  It's a little of both.  All of the projects currently using Europa are stable and aren't driving change.  I'm the only core developer still at NASA and still fiddling with it, and while I sometimes hack on it in my spare time, that's very subject to how much spare time there is.  I can probably spend official time on bug fixes if users request them, though, and I welcome pull requests.

I really can't tell you if starting a new application with it is a good idea.  I'd say it depends a lot on the needs of the application.

**Comment by rvlander** [comment]
Hi @miatauro-NASA and thanks for answering quicly!

Are new project needing an automated planner at NASA using Europa? More generally the automated planning field seem to be a bit dormant. ICAPS conferences seem sparse in time and planners issued from research do not seem very practical (maybe I am wrong). Maybe new projects prefer to implement domain dependent planners from scratch?

**Comment by miatauro-NASA** [comment]
NASA isn't a single unified thing, exactly, and I don't keep a close eye on what's going on at other NASA centers, so I can't speak with authority about planning applications at NASA in general.  Here at the Ames Research Center, there are a couple of upcoming projects that might use Europa, but I don't know if they'd require any core development, and it's not even certain that they'll go with Europa.  Outside NASA, the only ongoing project that I know of that uses it is TREX, which is still using it to drive autonomous submersibles.  Now that I think about it, though, I haven't heard from them in a while.
For my own group, we've shifted closer to the execution side of things for the moment.  
I'll speculate wildly and without analysis that, if the planning community seems a little dry, it's probably because the deepest pool of AI money is in machine learning right now.

**Comment by rvlander** [comment]
OK. Thanks for your answers.
