### ISSUE TITLE
Equality constraint between a temporal variable and a non-temporal variable causes segfault

### ISSUE THREAD

**Issue by miatauro-NASA** [nasa/europa#74]
_From [None](https://code.google.comNone) on May 04, 2010 08:30:56_

_Original issue: http://code.google.com/p/europa-pso/issues/detail?id=74_

**Comment by miatauro-NASA** [comment]
I added a test case for this in 39bd6b9, but it doesn't seem to reproduce the problem.  Closing this for the moment.

**Comment by phmorris** [comment]
We have seen this problem before.  There was a discussion about it on 
the Google feedback from users.  The issue was that the non-temporal 
variable increment needs to be made into a temporal variable by using 
the temporalDistance constraint rather than the Equal or eqSum 
constraints.  (Not all constraint network variables are temporal 
variables.)  Maybe it was fixed.

Paul

**Comment by phmorris** [comment]
https://groups.google.com/forum/?hl=en#!topic/europa-users/_v7kLMXB3-c

You need to use the algebraic syntax for the constraint in order to 
reproduce the segfault.  If you use the relational syntax, it coerces 
the non-temporal variable into a temporal variable and works correctly.

The newer algebraic syntax apparently overlooked the need to coerce 
non-temporal variables when combined with temporal variables.

Paul

**Comment by miatauro-NASA** [comment]
Aha!  I'll reopen.

**Comment by miatauro-NASA** [comment]
I haven't checked in the tests yet, but I've tried a few additional ways of reproducing this and I believe it's fixed.  Looking at Axel's original post that you linked, I think the Windows libraries were being used, which may be well out of date at this point.
